#!/usr/bin/env bash
# Deploy the public static site to Cloudflare Pages (the live elcensuradoweb.com).
#
# Generates a fresh snapshot from the local sqlite DB, copies the media, writes the
# root redirect and the cache headers (deploy/CACHING.md), and pushes to the Pages
# project. wrangler is authed via OAuth (`wrangler login` once), so no API token is
# needed here.
#
# The Cloudflare account id is NOT baked into this public repo: set CLOUDFLARE_ACCOUNT_ID
# in your .env (it is a host identifier, not a secret, but it stays out of git). The site
# domain and Pages project default to production and can be overridden by env.
#
# IMPORTANT: -page-size MUST match production (6). The generator default is larger and a
# big-page landing renders wrong against the current corpus, so always pass 6 here.
set -euo pipefail
cd "$(dirname "$0")/.."

# Pull non-secret config from .env if present (CLOUDFLARE_ACCOUNT_ID lives there).
if [ -f .env ]; then set -a; . ./.env; set +a; fi

ACCT="${CLOUDFLARE_ACCOUNT_ID:-}"
if [ -z "$ACCT" ]; then
  echo "FATAL: set CLOUDFLARE_ACCOUNT_ID in .env (or the environment) before deploying." >&2
  echo "       It is your Cloudflare account id, visible in the dashboard URL." >&2
  exit 1
fi
PROJECT="${DEPLOY_PROJECT:-elcensuradoweb}"
BASE_URL="${DEPLOY_BASE_URL:-https://elcensuradoweb.com}"
PAGE_SIZE="${PAGE_SIZE:-6}"

echo "[1/6] clean dist (root-owned leftovers need a root container)"
docker run --rm -v "$PWD:/w" busybox rm -rf /w/dist
mkdir -p dist && chmod 777 dist

echo "[2/6] generate -> dist (fresh compile, page-size $PAGE_SIZE, base $BASE_URL)"
docker compose run --rm -v "$PWD/dist:/out" generate \
  go run ./cmd/censurado/generate -db /data/censurado.db -out /out \
  -base-url "$BASE_URL" -page-size "$PAGE_SIZE"

echo "[3/6] copy media (/media/<sha>.png)"
docker run --rm -v "$PWD/dist:/out" -v "$PWD/data/media:/srcmedia:ro" busybox \
  sh -c "mkdir -p /out/media && cp /srcmedia/*.png /out/media/ 2>/dev/null || true"

echo "[4/6] _redirects + _headers (root index; cache policy = deploy/CACHING.md)"
printf '/    /latest/    302\n' > dist/_redirects
# HTML/CSS/JS/JSON live at stable (non-hashed) URLs with mutable bytes, so they must
# refetch after a deploy. "no-store" (not "no-cache") because iOS WebKit (Safari, and
# Brave/Chrome on iOS) does NOT reliably revalidate "no-cache" on reload: it serves a
# stale disk copy, so the site looks frozen on iPhone even after a manual refresh.
# "no-store" is the only directive iOS honors. Without this, Pages also defaults CSS/JS
# to max-age=14400 (4h), which cached even the refresh-poller script. /media/ is
# content-addressed so it stays immutable. Later rule wins, so /media/* comes last.
cat > dist/_headers <<'HEADERS'
/*
  Cache-Control: no-store
/media/*
  Cache-Control: public, max-age=31536000, immutable
HEADERS

# The reactions API (functions/api/reactions.js, the article like/dislike counter)
# needs a D1 binding, which Pages reads from wrangler.toml at deploy time. The file
# embeds the account-specific database id, so it is GENERATED here from .env and
# gitignored, exactly like _redirects/_headers above. One-time setup:
#   npx wrangler d1 create censurado-reactions   -> D1_REACTIONS_ID in .env
# Without D1_REACTIONS_ID the deploy still ships the function, which answers 503,
# and the frontend keeps the reactions bar hidden.
echo "[5/6] wrangler.toml (Pages config: reactions D1 binding)"
if [ -n "${D1_REACTIONS_ID:-}" ]; then
  # An empty salt would store bare sha256(IP) voter keys (enumerable over the whole
  # IPv4 space, de-anonymizing voters if the DB ever leaks), so refuse to deploy the
  # binding without one. Charset-restricted because the value lands inside a TOML
  # basic string below: a quote or backslash would corrupt the generated file.
  if [ -z "${REACTIONS_SALT:-}" ]; then
    echo "FATAL: REACTIONS_SALT is empty but D1_REACTIONS_ID is set." >&2
    echo "       Mint one (e.g. openssl rand -hex 16), put it in .env, keep it stable." >&2
    exit 1
  fi
  case "$REACTIONS_SALT" in *[!A-Za-z0-9_-]*)
    echo "FATAL: REACTIONS_SALT may only contain [A-Za-z0-9_-]." >&2
    exit 1;;
  esac
  cat > wrangler.toml <<EOF
# GENERATED by deploy/deploy-cdn.sh on every deploy from .env; do not edit or commit.
name = "$PROJECT"
pages_build_output_dir = "dist"
compatibility_date = "2026-01-01"

[vars]
REACTIONS_SALT = "${REACTIONS_SALT:-}"

[[d1_databases]]
binding = "DB"
database_name = "${D1_REACTIONS_NAME:-censurado-reactions}"
database_id = "$D1_REACTIONS_ID"
EOF
else
  rm -f wrangler.toml
  echo "  D1_REACTIONS_ID not set: deploying without the reactions binding (the bar stays hidden)"
fi

echo "[6/6] wrangler deploy -> Pages project '$PROJECT' (branch main)"
CLOUDFLARE_ACCOUNT_ID="$ACCT" npx -y wrangler pages deploy dist \
  --project-name "$PROJECT" --branch main --commit-dirty=true
